services:
  backend:
    image: backend:0.2
    container_name: backend_service
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"