services:
  backend:
    image: backend:0.1
    container_name: backend_service
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"